### ISSUE TITLE
Draggable bug

### ISSUE THREAD

**Issue by falget** [kutlugsahin/ngx-smooth-dnd#1]
Hello, i found some bug when drag item. Test on demo page.
![draggable_bug](https://user-images.githubusercontent.com/3428704/38614162-cf8f6be2-3d94-11e8-8d75-ea6fb365ccf9.gif)
And in html i have this:
![html](https://user-images.githubusercontent.com/3428704/38614294-44b09bda-3d95-11e8-857c-40aee5180e28.png)

**Comment by kutlugsahin** [comment]
@falget Thanks for submitting the bug. Are there any console errors logged ?

**Comment by falget** [comment]
No any errors, only warning with:
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

**Comment by falget** [comment]
@kutlugsahin I also have this bug in own project.

**Comment by kutlugsahin** [comment]
Should be fixed in 0.1.3. For smooth-dnd it's 0.3.5

**Comment by alexandrakollarova** [comment]
@kutlugsahin Hi! I'm having the same error (and warning) - it is not fixed, do you any update on this?
